-- ============================================================
-- English ⇄ Mara Dictionary — Sample Seed Data
-- Replace with real Mara language data.
-- ============================================================

INSERT INTO dictionary (english_word, mara_word, part_of_speech, definition, example_sentence) VALUES
  ('water',    'tui',      'noun',      'A clear liquid essential for life.',                  'I need water to drink.'),
  ('fire',     'mei',      'noun',      'Combustion producing heat and light.',                'The fire keeps us warm.'),
  ('house',    'inn',      'noun',      'A building for human habitation.',                    'They built a new house.'),
  ('eat',      'cha',      'verb',      'To put food into the mouth and swallow it.',          'We eat rice every day.'),
  ('drink',    'dawn',     'verb',      'To take liquid into the mouth and swallow.',          'I drink water in the morning.'),
  ('go',       'kal',      'verb',      'To move from one place to another.',                  'Let us go to the market.'),
  ('come',     'ra',       'verb',      'To move toward the speaker.',                         'Please come here.'),
  ('good',     'tha',      'adjective', 'Of high quality or standard.',                        'This is a good book.'),
  ('bad',      'sia',      'adjective', 'Of poor quality or low standard.',                    'That was a bad idea.'),
  ('big',      'lian',     'adjective', 'Of considerable size or extent.',                     'The big tree fell down.'),
  ('small',    'te',       'adjective', 'Of a size that is less than normal.',                 'A small bird sat on the branch.'),
  ('person',   'pa',       'noun',      'A human being.',                                     'Each person has a name.'),
  ('child',    'nao',      'noun',      'A young human being.',                                'The child is playing outside.'),
  ('mother',   'nu',       'noun',      'A female parent.',                                    'My mother cooks for us.'),
  ('father',   'pa',       'noun',      'A male parent.',                                     'My father works in the field.'),
  ('sun',      'ni',       'noun',      'The star at the center of our solar system.',         'The sun rises in the east.'),
  ('moon',     'thla',     'noun',      'The natural satellite of the earth.',                 'The moon is bright tonight.'),
  ('rain',     'ruah',     'noun',      'Water falling from clouds.',                          'The rain has stopped.'),
  ('mountain', 'tlang',    'noun',      'A large natural elevation of earth.',                 'We climbed the mountain.'),
  ('river',    'tuipui',   'noun',      'A large natural stream of water.',                    'The river flows to the sea.'),
  ('one',      'khat',     'number',    'The number 1.',                                       'I have one book.'),
  ('two',      'hnih',     'number',    'The number 2.',                                       'She has two cats.'),
  ('three',    'thum',     'number',    'The number 3.',                                       'Three birds flew away.'),
  ('yes',      'aw',       'particle',  'Used to give an affirmative response.',               'Yes, I will come.'),
  ('no',       'aw lo',    'particle',  'Used to give a negative response.',                   'No, I cannot go today.'),
  ('love',     'hmangaih', 'verb',      'An intense feeling of deep affection.',               'I love my family.'),
  ('sleep',    'mut',      'verb',      'To rest with eyes closed and body inactive.',         'I sleep eight hours a night.'),
  ('see',      'hmu',      'verb',      'To perceive with the eyes.',                          'I can see the mountains from here.'),
  ('hear',     'hria',     'verb',      'To perceive with the ear.',                           'I hear the birds singing.'),
  ('speak',    'sawt',     'verb',      'To say something in order to convey information.',    'She speaks three languages.'),
  ('name',     'hming',    'noun',      'A word by which a person or thing is known.',         'What is your name?'),
  ('day',      'ni',       'noun',      'A period of twenty-four hours.',                      'Today is a beautiful day.'),
  ('night',    'zan',      'noun',      'The period of darkness between sunset and sunrise.',   'The stars shine at night.'),
  ('food',     'rawl',     'noun',      'Any substance consumed to provide nutrition.',         'We need food and water.'),
  ('road',     'kawng',    'noun',      'A wide way leading from one place to another.',       'The road is long and winding.'),
  ('thank you','ka lawm e','phrase',    'An expression of gratitude.',                          'Thank you for your help.'),
  ('friend',   'thiante',  'noun',      'A person with whom one has a bond of mutual affection.','She is my best friend.'),
  ('work',     'hnathawh', 'noun',      'Activity involving mental or physical effort.',        'Hard work pays off.'),
  ('land',     'ram',      'noun',      'The solid ground of the earth.',                       'This land is fertile.'),
  ('dog',      'ui',       'noun',      'A domesticated carnivorous mammal.',                   'The dog barked loudly.'),
  ('cat',      'chawmnu',  'noun',      'A small domesticated feline.',                         'The cat sits on the mat.'),
  ('bird',     'vate',     'noun',      'A warm-blooded egg-laying vertebrate with feathers.',  'A bird is singing in the tree.'),
  ('fish',     'sangha',   'noun',      'A limbless cold-blooded vertebrate animal with gills.', 'We caught a fish in the river.'),
  ('tree',     'thing',    'noun',      'A woody perennial plant.',                              'The tree is very old.'),
  ('flower',   'par',      'noun',      'The seed-bearing part of a plant.',                     'The flower smells sweet.'),
  ('sky',      'van',      'noun',      'The region of the atmosphere above the earth.',         'The sky is clear and blue.'),
  ('earth',    'leilung',  'noun',      'The planet on which we live.',                          'The earth is round.'),
  ('stone',    'lung',     'noun',      'A hard solid nonmetallic mineral matter.',               'He threw a stone into the water.'),
  ('hand',     'kut',      'noun',      'The end part of a person''s arm.',                      'Wash your hands before eating.'),
  ('eye',      'mit',      'noun',      'The organ of sight.',                                   'She has beautiful eyes.');
